module.exports = {
    login: 'DylanWalseth',
    id: 7492203,
    node_id: 'MDQ6VXNlcjc0OTIyMDM=',
    avatar_url: 'https://avatars1.githubusercontent.com/u/7492203?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/DylanWalseth',
    html_url: 'https://github.com/DylanWalseth',
    followers_url: 'https://api.github.com/users/DylanWalseth/followers',
    following_url:
        'https://api.github.com/users/DylanWalseth/following{/other_user}',
    gists_url: 'https://api.github.com/users/DylanWalseth/gists{/gist_id}',
    starred_url:
        'https://api.github.com/users/DylanWalseth/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/DylanWalseth/subscriptions',
    organizations_url: 'https://api.github.com/users/DylanWalseth/orgs',
    repos_url: 'https://api.github.com/users/DylanWalseth/repos',
    events_url: 'https://api.github.com/users/DylanWalseth/events{/privacy}',
    received_events_url: 'https://api.github.com/users/DylanWalseth/received_events',
    type: 'User',
    site_admin: false,
    name: 'Dylan Walseth',
    company: 'twitter',
    blog: 'https://dylanwalseth.github.io/',
    location: 'Sunnyvale, CA',
    email: null,
    hireable: null,
    bio: null,
    public_repos: 19,
    public_gists: 0,
    followers: 18,
    following: 25,
    created_at: '2014-05-05T18:49:17Z',
    updated_at: '2019-06-06T23:27:14Z'
};